### ISSUE TITLE
Build on macOS

### ISSUE THREAD

**Issue by eliot-akira** [ArkScript-lang/Ark#87]
**Is your feature request related to a problem? Please describe.**

I followed the build steps on macOS, until `cmake --build build`. It ends with:

```sh
~/lisp/Ark/include/Ark/Utils.hpp:10:10: fatal error: 'filesystem' file not found
#include <filesystem>
         ^~~~~~~~~~~~
```

The comment on the next step ("works on Linux and on Windows") implies that the project is not meant to be built on macOS.

Is that the case, or perhaps I'm missing a dependency?

**Describe the solution you'd like**

I'd love to be able to play with ArkScript on macOS.

**Additional context**

As context, I'm pretty much a beginner with C++, so I have no clue whether `filesystem` is a platform-specific thing.

**Comment by SuperFola** [comment]
(I don't own a Mac myself so I had to do a bit of research before answering, sorry for the delay)

What is your version of clang? (you can check it using https://stackoverflow.com/questions/33603027/get-apple-clang-version-and-corresponding-upstream-llvm-version)

Some people told me it was working fine with clang 9.1, using the `std::filesystem` (it isn't a platform specific thing, it became standard in C++17)

**Comment by eliot-akira** [comment]
Thank you for looking into it - I'm mostly just curious to try the language (but that's how rabbit holes usually start! :).

Running `clang --version` gives me:

```
Apple LLVM version 10.0.1 (clang-1001.0.46.3)
Target: x86_64-apple-darwin18.2.0
```

I searched for more information about missing `std::filesystem`, and found a note: `libc++` on versions of macOS prior to 10.15 are lacking the filesystem implementation. I'm (still) running macOS 10.14 - apparently it's under `experimental/filesystem`. 

It sound like if I can run clang with option `-std=c++17`, it may work. I tried editing `CMakeLists.txt`, adding that option to `CMAKE_CXX_FLAGS`, and rebuilt make files. Nope, still can't find filesystem.

I grepped in the make files, and found this:

```
./CMakeFiles/Ark.dir/flags.make:5:CXX_FLAGS = -O3 -DNDEBUG -fPIE   -std=c++1z
```

This `-std=c++1z` looks like it's already targeting the latest c++ version.

---

OK, different approach based on a [similar issue thread](https://github.com/octobanana/fltrdr/issues/3).

```
brew install gcc
brew link gcc
ls -lA /usr/local/bin | grep gcc
```

In `CMakeLists.txt`

```
set (CMAKE_C_COMPILER /usr/local/bin/gcc-9)
set (CMAKE_CXX_COMPILER /usr/local/bin/g++-9)
```

Then rebuild

```
rm -rf build
cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -DARK_BUILD_EXE=1
cmake --build build
```

..And it works!

So, to avoid editing `CMakeLists.txt`, I can probably use aliases. Is there a way to set the default values of `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER` from outside the make file?
